### ISSUE TITLE
[Pipeline Core] Support for Pipeline Connectors

### ISSUE THREAD

**Issue by kowshikn** [opendistro-for-elasticsearch/simple-ingest-transformation-utility-pipeline#46]
<TBD> @yadavcbala

**Comment by yadavcbala** [comment]
PR #47 has the changes for above

**Comment by yadavcbala** [comment]
PR #47

**Comment by yadavcbala** [comment]
Re-Opening the update the issue with discussion

**Comment by yadavcbala** [comment]
### Background
As part of the definition of Sink - _defines one or more destinations to which a SITUP pipeline will publish the records. A sink destination could be services like elasticsearch, s3 or another SITUP pipeline. By using another SITUP pipeline as sink, we enable customers to chain multiple TI pipelines._

To allow defining pipeline as a sink, the source for the connecting pipeline also becomes a pipeline which demands a special type of plugin and is limited to this special use-case i.e. pipeline chaining. This lead to the above issue or requirement for having PipelineConnector.

### Current Pipeline Configuration
```
pipeline:
  name: otel-span
  source:
    apm_trace_source:
      server: "localhost"
      port: 9400
  buffer:
    bounded_blocking:
      buffer_size: 512
  processor:
    geoip:
      database: "/geo-ip.db"
    filter:
      fieldKey: "span_kind"
      fieldValue: "Client"
  sink:
    elasticsearch:
      hosts: ["https://search-sample-app-test.us-west-2.es.amazonaws.com"]
    s3:
      bucket: "global-bucket"
```
### Multiple/Updated Pipelines Configuration

```
pipeline-1:
  source:
    apm_trace_source:
      server: "localhost"
      port: 9400
  buffer:
    bounded_blocking:
      buffer_size: 512
  processor:
    transform:
      to: elasticsearch
  sink:
    pipeline:
      name: "pipeline-2"
  workers: 4
  delay: 500 #ms
      
pipeline-2:
  source:
    pipeline:
      name: "pipeline-1"
  buffer:
    bounded-blocking:
      buffer_size: 1024
  processor:
    geoip:
      database: "/geo-ip.db"
  sink:
    elasticsearch:
      hosts: ["https://search-sample-app-test.us-west-2.es.amazonaws.com"]
```

_The above sample is solely as an example and it does not cover all the nuances multiple pipelines brings to the table, Feel free to raise a question or comment_

### Pipeline Connector

PipelineConnector will be a special type of plugin which will be both `Source` and `Sink` and we will limit the possibilities of extending this connector i.e. we would not need more custom plugins for this special connector at the time of this writing. This will introduce a good number of ambiguous edge cases and below is my best attempt to cover/answer them, Please feel free to comment if I missed any

1. Orphan Pipelines

_What happens if there exists a pipeline which is not connected to any other pipeline, will it be marked as invalid_

```
pipeline-1:
  source:
    file:
  sink:
    pipeline:
      name: "pipeline-2"
      
pipeline-2:
  source:
    pipeline:
      name: "pipeline-1"
  buffer:
     bounded-blocking:
  sink:
    elasticsearch:
      hosts: ["localhost:9200"]

pipeline-3:
  buffer:
     sqs:
  sink:
    elasticsearch:
      hosts: ["localhost:9200"]
```

At the time of this writing, we will allow having such configuration as pipelines will be executed independently.

2. Other Validations
_below are some invalid configuration examples_

```
pipeline-1:
  source:
    file:
  sink:
    pipeline:
      name: "pipeline-2"
      
pipeline-2:
  source:
    pipeline:
      name: "pipeline-3" # invalid - expected pipeline-1
  buffer:
     bounded-blocking:
  sink:
    elasticsearch:
      hosts: ["localhost:9200"]
```

```
pipeline-1:
  source:
    file:
  sink:
    pipeline:
      name: "pipeline-2"
      
pipeline-2:
  source:
    apm-otel-trace-source: # invalid - expected pipeline type
      name: "pipeline-3" 
  buffer:
     bounded-blocking:
  sink:
    elasticsearch:
      hosts: ["localhost:9200"]
```
